GET http://localhost:3002/api/v1/test

###

POST http://localhost:3002/api/v1/register HTTP/1.1
Content-Type: application/json

{
  "email": "medic2242@medic.com",
  "username": "medic4222111",
  "password": "111111"
}

### 

POST http://localhost:3002/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "username": "bob",
  "password": "bob123"
}

### 

POST http://localhost:3002/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "username": "medic4222111",
  "password": "111111"
}